import {chromium,webkit} from '/Users/takahirokamino/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import {writeFileSync} from 'node:fs';
import {properties,queryCatalog} from '../../assets/land-payment-study/catalog.mjs';
const base=process.env.STUDY_URL||'http://127.0.0.1:4191/land-payment-study.html',out='qa/map-pc-school-20260908/',prefix=process.env.STUDY_URL?'hosted-':'local-';const checks=[],shots=[],errors=[];
const configurations=[[chromium,'chrome-pc',1440,900],[chromium,'chrome-short',1280,720],[chromium,'chrome-small',1024,768],[webkit,'safari-pc',1280,800],[webkit,'safari-sp',390,844],[webkit,'safari-small',320,740]];
for(const [engine,label,width,height] of configurations.filter(c=>!process.env.CASE||c[1]===process.env.CASE)){
 const b=await engine.launch(engine===chromium?{executablePath:'/Users/takahirokamino/.agent-browser/browsers/chrome-149.0.7827.55/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing'}:{});
 const context=await b.newContext({viewport:{width,height},deviceScaleFactor:1,isMobile:width<900,hasTouch:width<900,reducedMotion:'reduce'});const p=await context.newPage();p.setDefaultTimeout(12000);p.on('pageerror',e=>errors.push({label,error:e.message}));
 // Test instrumentation retains the returned Leaflet instance; interaction uses real controls.
 await p.route('**/assets/land-payment-study/app.mjs',async route=>{const r=await route.fetch();await route.fulfill({response:r,body:`const qaCreateMap=L.map;L.map=function(...args){const instance=qaCreateMap.apply(this,args);globalThis.__qaMap=instance;return instance;};\n`+await r.text()});});
 const check=(name,ok,details)=>{checks.push({label,name,ok,details});if(!ok)throw Error(label+': '+name+' '+JSON.stringify(details));};
 const settle=()=>p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
 const ids=()=>p.locator('#list .property-card').evaluateAll(ns=>ns.map(n=>n.dataset.id));
 const open=async hash=>{await p.goto(base+hash,{waitUntil:'domcontentloaded'});if(hash.startsWith('#/property/'))await p.locator('.property-detail').waitFor();else await p.locator('#count').filter({hasText:/件/}).waitFor();await settle();};
 const mapVisible=()=>p.locator('#map-shell').isVisible();
 const inBounds=async rows=>p.evaluate(rows=>{const m=globalThis.__qaMap;return m?rows.every(p=>m.getBounds().contains([p.lat,p.lng])):false},rows);
 const pins=()=>p.locator('[data-pin],[data-cluster]').evaluateAll(ns=>ns.flatMap(n=>n.dataset.pin?[n.dataset.pin]:n.dataset.cluster.split(',')));
 const shot=async(name,selector)=>{if(selector)await p.locator(selector).scrollIntoViewIfNeeded();await settle();await p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].filter(i=>{const r=i.getBoundingClientRect();return r.height&&r.bottom>0&&r.top<innerHeight}).map(i=>Promise.race([i.decode().catch(()=>{}),new Promise(r=>setTimeout(r,3500))])));});const path=out+prefix+label+'-'+name+'.png';await p.screenshot({path,scale:'css'});const overflow=await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth);check(name+' no horizontal overflow',!overflow);shots.push({label,name,path,width,height});};
 try{
  await open('#/search?view=list');check('list entry has 40 listings',(await ids()).length===40);
  check('desktop list entry also has map; mobile keeps list mode',await mapVisible()===(width>900));
  if(width<=900)await p.locator('#map-view').click();await p.locator('.leaflet-tile-loaded').first().waitFor();await settle();check('all 40 source coordinates within initial map',await inBounds(properties));check('all listing IDs appear in map markers',(await pins()).length===40);
  if(width>900){const r=await p.locator('#map-shell').boundingBox();check('entire map in first viewport',r.y>=0&&r.y+r.height<=height,{y:r.y,height:r.height,viewport:height});check('desktop mode switch hidden',!await p.locator('#map-view').isVisible());}
  await shot('map');
  if(width>900){const zoom=await p.evaluate(()=>__qaMap.getZoom());await p.mouse.move(width/2,500);await p.mouse.wheel(0,1100);await p.waitForFunction(()=>scrollY>900);check('map scrolls offscreen',await p.locator('#map-shell').evaluate(el=>el.getBoundingClientRect().bottom<0));check('wheel scroll did not zoom map',await p.evaluate(()=>__qaMap.getZoom())===zoom);check('list has no independent scroll region',await p.locator('.list-panel').evaluate(el=>getComputedStyle(el).overflowY==='visible'));await p.evaluate(()=>scrollTo(0,0));await p.locator('.results-jump').click();}
  else await p.locator('#list-view').click();
  await shot('list',width>900?'.results-heading':undefined);
  for(const sort of ['primary','junior','price','area','walk','updated','region']){await p.locator('#sort').selectOption(sort);check(sort+' ordering matches published data',JSON.stringify(await ids())===JSON.stringify(queryCatalog({},sort).map(r=>r.property.id)));}
  await p.locator('#sort').selectOption('junior');check('school missing entry last',(await ids()).at(-1)==='s78578283');check('missing school copy says unavailable',await p.locator('#list [data-id=s78578283] .card-schools').innerText().then(t=>t.includes('距離の情報なし')));
  await p.locator('#open-filters').click();await p.locator('#school-filters summary').click();await p.locator('[name=primary]').selectOption('800');await p.locator('[name=junior]').selectOption('1200');await p.locator('#filter-dialog').evaluate(el=>el.scrollTop=el.scrollHeight);await settle();await p.locator('[name=primary]').click({trial:true});check('school selector reachable above sticky actions',true);await shot('school-filter');await p.locator('#filter-form [type=submit]').click();
  const expected=queryCatalog({primary:800,junior:1200},'junior').map(r=>r.property.id);check('combined school filter',JSON.stringify(await ids())===JSON.stringify(expected));check('filters in URL',p.url().includes('primary=800')&&p.url().includes('junior=1200'));
  await p.reload({waitUntil:'domcontentloaded'});await p.locator('#count').filter({hasText:expected.length+'件'}).waitFor();await settle();check('reload retains sort and school conditions',JSON.stringify(await ids())===JSON.stringify(expected)&&await p.locator('#sort').inputValue()==='junior');
  if(width>900){await p.locator('.results-jump').click();await shot('school-results','.results-heading');check('results jump reveals list heading',await p.locator('.results-heading').evaluate(el=>el.getBoundingClientRect().top>=0&&el.getBoundingClientRect().top<innerHeight),await p.evaluate(()=>({y:scrollY,top:document.querySelector('.results-heading').getBoundingClientRect().top,active:document.activeElement.outerHTML,ready:document.readyState}))); }else await shot('school-results');await shot('school-card','#list .property-card:first-child .card-schools');
  await p.locator('[data-remove-filter=primary]').click();check('remove one school condition retains other',!p.url().includes('primary=')&&p.url().includes('junior=1200'));
  await p.locator('#open-filters').click();check('active school section reopens',await p.locator('#school-filters').evaluate(el=>el.open));await p.locator('[name=region][value="奈良市"]').check();await p.locator('#filter-form [type=submit]').click();await p.locator('#open-filters').click();await p.locator('#filter-form [type=reset]').click();check('form reset clears previously checked regions and school options',await p.locator('#filter-form').evaluate(f=>![...f.querySelectorAll('[name=region]')].some(n=>n.checked)&&f.elements.primary.value===''&&f.elements.junior.value===''));await p.locator('#filter-form [type=submit]').click();check('reset restores full catalogue',(await ids()).length===40);
  await open('#/search?region='+encodeURIComponent('生駒市')+'&price=1000&area=180&primary=800&junior=800');check('empty result has zero listings',(await ids()).length===0);check('empty result removes all map markers',(await pins()).length===0);await shot('empty');await p.locator('#map-empty [data-reset-filters]').click();check('empty reset restores40',(await ids()).length===40);check('empty reset refits all40',await inBounds(properties));
  // Zoom and drag are actual user input; the map fit action restores the source extent.
  await p.locator('.leaflet-control-zoom-in').click();await p.locator('#map-fit').click();check('whole-map button restores every result',await inBounds(properties));
  if(width>900){const r=await p.locator('#map-shell').boundingBox();await p.mouse.move(r.x+r.width*.6,r.y+r.height*.65);await p.mouse.down();await p.mouse.move(r.x+r.width*.6+90,r.y+r.height*.65,{steps:8});await p.mouse.up();await p.locator('#search-bounds').waitFor();await p.locator('#search-bounds').click();check('drag area enters URL',p.url().includes('bounds='));const boundedUrl=p.url(),boundedIds=await ids();if(boundedIds.length){await p.locator(`#list [data-property=${boundedIds[0]}]`).last().click();await p.locator('.property-detail').waitFor();await p.goBack();await p.locator('#search-screen').waitFor();await settle();check('back retains rounded map bounds and results',p.url()===boundedUrl&&JSON.stringify(await ids())===JSON.stringify(boundedIds));}await p.locator('[data-reset-filters].clear-all').click();}
  if(width<=900)await p.locator('#list-view').click();else await p.locator('.results-jump').click();
  const first=(await ids())[0];await p.locator(`#list [data-map-select=${first}]`).click();check('list selection opens selected card',await p.locator('#selected-card').isVisible());check('list selection returns map to view',await mapVisible()&&await p.locator('#map-shell').evaluate(el=>el.getBoundingClientRect().top>=-1&&el.getBoundingClientRect().top<innerHeight));
  await p.locator('#selected-card [data-save]').click();check('save state reflected',await p.locator('#saved-count').innerText()==='1');await p.locator('#selected-card [data-property]').click();await p.locator('.property-detail').waitFor();check('detail preserves selected listing',p.url().endsWith('/'+first));await p.goBack();await p.locator('#selected-card').waitFor();check('back retains selected listing',await p.locator('#selected-card [data-property]').getAttribute('data-property')===first);await p.locator('#close-card').click();
  if(width>900){await p.setViewportSize({width:390,height:844});await settle();check('PC to mobile restores mode switch',await p.locator('#list-view').isVisible());await p.locator('#list-view').click();await p.setViewportSize({width,height});await settle();check('mobile list to PC still shows map',await mapVisible());check('resize keeps 40 records',(await ids()).length===40);}
  await p.locator('#map-expand').click();check('fullscreen is user-initiated dialog',await p.locator('#map-shell').getAttribute('aria-modal')==='true');await p.keyboard.press('Escape');check('fullscreen closes without fixed map',!await p.locator('#map-shell').evaluate(el=>el.classList.contains('is-fullscreen')));
  if(label==='chrome-pc'||label==='safari-sp'){
   await open('#/property/s74168777');await p.locator('.property-buttons [data-save]').click();await open('#/property/s77384816');await p.locator('.property-buttons [data-save]').click();await p.locator('.saved-nav').click();for(const id of ['s74168777','s77384816'])await p.locator(`[data-compare=${id}]`).check();await p.locator('#compare-tray [data-page=compare]').click();check('compare retains chosen2',await p.locator('.comparison-head h2').count()===2);check('comparison contains school distance unit',await p.locator('.comparison-wrap').count()?await p.locator('.comparison-wrap').innerText().then(t=>t.includes('1,300m')):await p.locator('body').innerText().then(t=>t.includes('1,300m')));
   await open('#/property/s74168777');await p.locator('[data-estimate]').first().click();check('land price prefilled accurately',await p.locator('[name=landMan]').inputValue()==='2180');await p.locator('[name=houseId][value=kyo]').check();await p.locator('#estimate-form [type=submit]').click();await p.locator('#monthly-value').waitFor();check('estimate result rendered',await p.locator('#monthly-value').innerText().then(t=>/[0-9]/.test(t)));await shot('result');
  }
  check('no browser exceptions',!errors.some(e=>e.label===label));
 }finally{await b.close();writeFileSync(out+prefix+'browser.json',JSON.stringify({base,checks,shots,errors},null,2));}
}
// A separate context tests total tile failure without changing any live service.
const b=await chromium.launch({executablePath:'/Users/takahirokamino/.agent-browser/browsers/chrome-149.0.7827.55/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing'});try{const p=await b.newPage({viewport:{width:1280,height:720}});await p.route('**/cyberjapandata.gsi.go.jp/**',r=>r.abort());await p.goto(base+'#/search',{waitUntil:'domcontentloaded'});await p.locator('#map-error').waitFor();await p.locator('#fallback-list').click();const ok=await p.locator('#list .property-card').count()===40&&await p.locator('#property-results').evaluate(el=>el.getBoundingClientRect().top>=0&&el.getBoundingClientRect().top<innerHeight);checks.push({label:'failure',name:'tile failure leads to usable list',ok});if(!ok)throw Error('fallback failed');}finally{await b.close();writeFileSync(out+prefix+'browser.json',JSON.stringify({base,checks,shots,errors},null,2));}
console.log(JSON.stringify({checks:checks.length,failures:checks.filter(c=>!c.ok),screenshots:shots.length,errors}));
