import test from 'node:test';
import assert from 'node:assert/strict';
import {createStore,normalizeState,createDraft,sanitizeFilters,SAVED_KEY} from '../../assets/land-payment-study/state.mjs';
import {properties,property,validateCatalog,queryCatalog,estimateFor,catalogRevision} from '../../assets/land-payment-study/catalog.mjs';
import {parseRoute,routeHash} from '../../assets/land-payment-study/router.mjs';
import {buildInquiry,validateInquiry,inquiryText} from '../../assets/land-payment-study/inquiry-contract.mjs';
import handler from '../../api/property-inquiries.mjs';
const mem=()=>{const m=new Map();return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v)};};
const make=()=>createStore(mem(),mem()),A='s74168777',B='s76455797';
const common={houseId:'kyo',cashMan:'500',years:35,financeId:'nanto',destinations:['大阪難波','本町'],arrival:'平日 8:30着'};
test('40 source records keep no invented plot and valid ranges',()=>{assert.equal(properties.length,40);assert.deepEqual(validateCatalog(),[]);assert.ok(properties.every(p=>p.plotId===null&&p.availability==='unverified'));});
test('new state has no selection and keeps independent concepts',()=>{const s=make().get();assert.equal(s.search.selectedId,null);assert.deepEqual(s.compareIds,[]);assert.equal(s.common.houseId,null);});
test('search excludes bad regions and bounds',()=>{assert.deepEqual(sanitizeFilters({regions:['生駒市','bad','生駒市'],price:666,walk:10,bounds:{north:1,south:50,east:135,west:134}}),{regions:['生駒市'],walk:10});});
test('rail station filter excludes bus-stop minutes',()=>{assert.ok(!queryCatalog({walk:10},'walk').some(r=>r.property.id==='s77151550'));});
test('combined range criteria do not assert verified plot',()=>{const rows=queryCatalog({price:2200,area:180},'price');assert.equal(rows.find(r=>r.property.id===A).matchStatus,'plot-unverified');});
test('saving persists in same device across sessions',()=>{const a=mem(),b=mem(),s=createStore(a,b);s.toggle(A);assert.equal(createStore(mem(),b).has(A),true);s.toggle(A);assert.equal(createStore(mem(),b).has(A),false);});
test('blocked storage does not stop search and temporary saves',()=>{const blocked={getItem(){throw Error();},setItem(){throw Error();}},s=createStore(blocked,blocked);s.toggle(A);assert.ok(s.has(A));assert.equal(s.capabilities().savedAvailable,false);});
test('malformed storage recovers',()=>{const a=mem();a.setItem('yamato-land-study:session:v2','{broken');assert.equal(createStore(a,mem()).get().search.selectedId,null);});
test('snapshot restores source and estimate context separately from saved candidates',()=>{const s=make();s.update(st=>{st.search.selectedId=A;st.common={...common};});const snap=s.snapshot();s.toggle(B);s.update(st=>{st.search.selectedId=B;st.common.years=40;});s.restore(snap);assert.equal(s.get().search.selectedId,A);assert.equal(s.get().common.years,35);assert.ok(s.has(B));});
test('draft retains house and loan on return while new drafts inherit common',()=>{const s=make();let a,b;s.update(st=>{st.common={...common};a=createDraft(st,A);a.common.financeId='flat-b';b=createDraft(st,B);});assert.equal(createDraft(s.get(),A).common.financeId,'flat-b');assert.equal(b.common.financeId,'nanto');});
test('URL contains only public search conditions',()=>{const s=make().get();s.common={...common};s.search.filters={regions:['生駒市'],price:1500};s.search.view='list';const h=routeHash({page:'search'},s);assert.equal(h.includes('大阪'),false);const r=parseRoute(h);assert.deepEqual(r.filters,s.search.filters);assert.equal(r.view,'list');});
test('bad route identifiers do not become DOM content',()=>{assert.equal(parseRoute('#%bad').page,'search');assert.deepEqual(parseRoute('#/compare?ids=bad,'+A).ids,[A]);});
test('known amortization matches prior independent fixture',()=>assert.equal(estimateFor(A,common,2180,'2026-09-07').result.paymentYen,115023));
test('expired rate produces error without a current result',()=>assert.ok(estimateFor(A,common,2180,'2026-10-01').error.includes('適用期間外')));
test('loan term incompatibility is explicit',()=>assert.ok(estimateFor(A,{...common,financeId:'flat-a',years:40},2180,'2026-09-07').error));
test('1498 budget is not rounded without user decision',()=>assert.ok(estimateFor(null,{...common,cashMan:'0'},1498,'2026-09-07').error));
test('no loan has zero payment and fee',()=>{const o=estimateFor(A,{...common,cashMan:'4660'},2180,'2026-09-07');assert.equal(o.result.paymentYen,0);assert.equal(o.result.feeYen,0);});
const body=()=>{const s=make();s.update(st=>{st.common={...common};st.inquiry={ids:[A,B],draftId:null,wishes:['通勤の経路・時間']};});return buildInquiry(s.get());};
test('inquiry preserves IDs common preferences and estimates',()=>{const b=body();assert.deepEqual(validateInquiry(b).candidateIds,[A,B]);assert.equal(b.estimates.length,2);assert.equal(b.preferences.destinations[1],'本町');assert.match(inquiryText(b),/未送信/);assert.match(inquiryText(b),/建物プラン：京/);});
test('server recalculates submitted amounts',()=>{const b=body();b.estimates[0].paymentYen=1;b.estimates[0].input.buildingMan=1;assert.equal(validateInquiry(b).estimates[0].paymentYen,115023);});
test('unknown candidates and stale revision are rejected',()=>{const b=body();b.candidates[0].dataRevision='old';assert.throws(()=>validateInquiry(b));b.candidates[0].dataRevision=catalogRevision;b.candidates[0].publicId='bad';assert.throws(()=>validateInquiry(b));});
test('non-numeric/null cash and duplicate estimates are rejected',()=>{const b=body();b.estimates[0].input.cashMan=null;assert.throws(()=>validateInquiry(b));const c=body();c.estimates[1]=c.estimates[0];assert.throws(()=>validateInquiry(c));});
test('wishes and invalid budget emptiness survive normalization',()=>{const s=make().get();s.inquiry={ids:[A],wishes:['見学を希望'],draftId:null};s.budgets[A]='';const n=normalizeState(s);assert.deepEqual(n.inquiry.wishes,['見学を希望']);assert.equal(n.budgets[A],'');});
const request=async(method,body)=>{let status=200,value,headers={};await handler({method,body},{setHeader:(k,v)=>headers[k]=v,status(n){status=n;return this;},json(v){value=v;return this;}});return {status,value,headers};};
test('test API validates but never pretends storage or delivery',async()=>{const r=await request('POST',{...body(),dryRun:true});assert.equal(r.status,200);assert.equal(r.value.stored,false);assert.equal(r.value.sent,false);assert.equal(r.headers['Cache-Control'],'no-store');});
test('real submission remains explicitly unavailable',async()=>{const r=await request('POST',body());assert.equal(r.status,503);assert.equal(r.value.sent,false);});
test('API refuses personal contact while receiver disconnected',async()=>assert.equal((await request('POST',{...body(),contact:{name:'test'}})).status,503));
test('API handles invalid JSON method and size',async()=>{assert.equal((await request('GET',{})).status,405);assert.equal((await request('POST','{')).status,400);assert.equal((await request('POST','x'.repeat(21000))).status,413);});

test('inquiry explains expired estimates instead of silently omitting them',()=>{const s=make();s.update(st=>{st.common={...common};st.inquiry={ids:[A],draftId:null,wishes:[]};});const b=buildInquiry(s.get(),'2026-10-01');assert.equal(b.estimates.length,0);assert.equal(b.estimateIssues.length,1);assert.match(inquiryText(b),/適用期間外/);});
test('clearing conditions leaves saved candidates and no stored commute destinations',()=>{const s=make();s.toggle(A);s.update(st=>{st.common={...common};createDraft(st,A);});s.clearConditions();assert.ok(s.has(A));assert.deepEqual(s.get().common.destinations,['','']);assert.deepEqual(s.get().drafts,{});});

test('history cannot restore conditions after explicit reset',()=>{const s=make();s.update(st=>{st.common={...common};createDraft(st,A);});const old=s.snapshot();s.clearConditions();s.restore(old);assert.equal(s.get().common.houseId,null);assert.deepEqual(s.get().drafts,{});});
