import {chromium} from '/Users/takahirokamino/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';
const b=await chromium.launch();const results=[];
for(const width of [1440,390]){const p=await b.newPage({viewport:{width,height:width===1440?1000:844},reducedMotion:'reduce'});await p.goto('http://127.0.0.1:8955/kodawari.html');await p.evaluate(()=>document.fonts.ready);await p.locator('#catTocOpen').click();await p.locator('#catToc a[href="#catalog-stedia"]').click();await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>window.__catalogReader.current()),'catalog-stedia');
const button=p.locator('#catalog-stedia [data-cr-zoom]').first();await button.click();await p.locator('#crLightbox').waitFor({state:'visible'});await p.locator('[data-cr-zoom-in]').click();await p.locator('[data-cr-zoom-reset]').click();await p.keyboard.press('Escape');await p.locator('#crLightbox').waitFor({state:'hidden'});await p.waitForTimeout(150);assert.equal(await button.evaluate(e=>e===document.activeElement),true);
await p.evaluate(()=>window.__catalogReader.go('catalog-compare-water'));await p.waitForTimeout(100);if(width<821){await p.locator('#catalog-compare-water .cr-table-toggle').click();assert.equal(await p.locator('#catalog-compare-water .cr-table-scroll').evaluate(e=>e.scrollWidth>e.clientWidth),true);await p.locator('#catalog-compare-water .cr-table-toggle').click();}
await p.goBack();await p.waitForTimeout(150);assert.equal(await p.evaluate(()=>window.__catalogReader.current()),'catalog-stedia');
for(const id of ['stedia','compare-water','warranty']){await p.evaluate(id=>window.__catalogReader.go('catalog-'+id),id);await p.waitForTimeout(100);await p.screenshot({path:`qa/catalog-adopted-20260909/evidence/prototype-${id}-${width}.png`});}
results.push({width,toc:true,zoomResetEscapeFocus:true,history:true,comparison:true});await p.close();}await b.close();await writeFile('qa/catalog-adopted-20260909/prototype-check.json',JSON.stringify(results,null,2));console.log(results);
