import fs from 'node:fs';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
const dir='qa/release-washi-voice-20260907';
const baseline=path=>execFileSync('git',['show',`f425a17:${path}`]);
const hash=data=>crypto.createHash('sha256').update(data).digest('hex');
const base=baseline('index.html').toString(), now=fs.readFileSync('index.html','utf8');
const section=(html,id)=>html.match(new RegExp(`<section[^>]*id="${id}"[\\s\\S]*?</section>`))?.[0];
const hero=section(now,'top');
assert(hero);assert.equal(hero,section(base,'top'),'Existing FV stays byte-identical');
const files=['v1top/index.html','works.html','kodawari.html','voice.html','data/voices.json','assets/top-renewal/hero.js','assets/fv_research_20260904/approved-hero.css','assets/top-renewal/nara-atlas/atlas.js','assets/top-renewal/guide-maquette/guide.css','api/instagram.js','lib/instagram.cjs'];
const preserved=files.map(path=>{const actual=fs.readFileSync(path);assert.equal(hash(actual),hash(baseline(path)),`Preserve ${path}`);return {path,sha256:hash(actual)};});
const originalVoice=section(fs.readFileSync('index-voice-reference-preview.html','utf8'),'voice');
const strip=html=>html.replace(/<span class="wg-[^"]+" aria-hidden="true"><\/span>/g,'').replace('voice-reference wg-section wg-white','voice-reference');
assert.equal(strip(section(now,'voice')),originalVoice,'Adopt latest voice exactly except decoration');
assert(fs.readFileSync('assets/top-renewal/voice-reference/voice.css','utf8').includes('.voice-reference__quote{font-size:11px;'),'User-specified mobile font');
const manifest=JSON.parse(fs.readFileSync('qa/checkpoint-20260906/package.json')).files;
assert(!manifest.some(f=>/staff|FV_Bright|3[Dd]/.test(f.path)),'Exclude ongoing staff/FV/3D');
const result={date:new Date().toISOString(),baseline:'f425a17',unchangedHeroSha256:hash(hero),preserved,voiceDonorMatched:true,excludedRuntimeAssets:true,runtimeFiles:manifest.length};
fs.writeFileSync(`${dir}/protection-report.json`,JSON.stringify(result,null,2)+'\n');
console.log(JSON.stringify(result));
