import {chromium,webkit} from '/Users/takahirokamino/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import fs from 'node:fs';import assert from 'node:assert/strict';
const q='qa/visit-adopted-release-20260910',out=process.env.QA_OUT||`${q}/local`;fs.mkdirSync(out,{recursive:true});const results=[];
for(const [engine,width,height,motion] of [[chromium,1440,778,'no-preference'],[webkit,390,844,'reduce']]){
 const b=await engine.launch();const p=await b.newPage({viewport:{width,height},reducedMotion:motion});const errors=[];p.on('pageerror',e=>errors.push(e.message));const attempts=[];p.on('request',r=>{if(r.method()!=='GET')attempts.push({url:r.url(),method:r.method()});});
 await p.goto(''+(process.env.QA_BASE||'http://127.0.0.1:8961')+'/index.html#visit');await p.evaluate(()=>document.fonts.ready);await p.locator('#visit .va26__scene img').evaluate(e=>e.decode());
 const geometries=await p.evaluate(()=>{const s=document.querySelector('#visit'),r=s.getBoundingClientRect(),h=document.querySelector('.site-header').getBoundingClientRect();return{height:r.height,header:h.height,overflow:document.documentElement.scrollWidth-innerWidth,copy:s.textContent,photos:[...s.querySelectorAll('img')].map(i=>({loaded:i.complete&&i.naturalWidth>0,src:i.currentSrc})),links:[...s.querySelectorAll('a')].map(a=>({text:a.textContent.trim(),href:a.getAttribute('href'),contact:a.dataset.contact,rect:a.getBoundingClientRect().toJSON()}))}});assert.equal(geometries.overflow,0);assert(geometries.photos.every(i=>i.loaded));for(const l of geometries.links)assert(l.rect.height>=44);assert.equal(geometries.links.at(-1).href,'tel:0742361123');
 const actions=[];for(const kind of ['reserve','docs']){
  const trigger=p.locator(`#visit [data-contact="${kind}"]`);await trigger.click();assert(await p.locator('#contactDialog').evaluate(e=>e.open));const title=await p.locator('#contactDialog h2').textContent();assert(title.includes(kind==='reserve'?'来場':'資料'));
  assert((await p.locator('#contactDialog').textContent()).includes('まだ送信できません'));const trap=await p.locator('#contactDialog').evaluate(e=>{const nodes=[...e.querySelectorAll('a[href],button:not([disabled]),[tabindex="0"]')].filter(n=>n.getClientRects().length);nodes.at(-1).focus();return{first:nodes[0].outerHTML,last:nodes.at(-1).outerHTML};});await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.activeElement.outerHTML),trap.first);await p.keyboard.press('Shift+Tab');assert.equal(await p.evaluate(()=>document.activeElement.outerHTML),trap.last);
  await p.screenshot({path:`${out}/dialog-${engine.name()}-${width}-${motion}-${kind}.png`,animations:'disabled'});await p.keyboard.press('Escape');assert.equal(await p.locator('#contactDialog').evaluate(e=>e.open),false);assert(await trigger.evaluate(e=>document.activeElement===e));
  await trigger.click();await p.locator('#contactDialog [data-close]').click();assert.equal(await p.locator('#contactDialog').evaluate(e=>e.open),false);assert(await trigger.evaluate(e=>document.activeElement===e));actions.push({kind,title,tabLoop:true,escapeFocusReturn:true,closeFocusReturn:true});
 }
 await p.evaluate(()=>{document.documentElement.style.scrollBehavior='auto';scrollTo({top:scrollY+document.querySelector('#visit').getBoundingClientRect().top-document.querySelector('.site-header').getBoundingClientRect().height,behavior:'instant'});});await p.waitForTimeout(150);await p.screenshot({path:`${out}/final-${engine.name()}-${width}-${motion}.png`,animations:'disabled'});
 assert.equal(errors.length,0);assert.equal(attempts.length,0);results.push({engine:engine.name(),width,height,motion,geometries,actions,errors,nonGetRequests:attempts});await b.close();console.log(`${engine.name()} ${width} ${motion}: actions and layout checked`);
}
fs.writeFileSync(`${out}/interaction.json`,JSON.stringify(results,null,2));
