// Shared content is rendered once for both viewport modes; no client fetch is needed to read it.
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const data=JSON.parse(readFileSync('data/catalog-content.json','utf8'));
const assets=JSON.parse(readFileSync('qa/catalog-adopted-20260909/asset-manifest.json','utf8'));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const links=(items=[])=>items.length?`<nav class="cr-links" aria-label="関連するご案内">${items.map(([url,label])=>`<a href="${esc(url)}">${esc(label)} <span aria-hidden="true">↗</span></a>`).join('')}</nav>`:'';
function photo(a,caption,hero=false){const x=assets[a];if(!x)throw Error('Asset missing: '+a);const zoom=x.width>350&&!['A15','A16'].includes(a);return `<figure class="cr-figure${hero?' cr-hero-photo':''}${x.width<1000?' cr-native':''}" style="--cr-native-width:${x.width}px"><${zoom?'button type="button" class="cr-photo-button" data-cr-zoom aria-label="'+esc(caption)+'を拡大"':'div class="cr-photo-static"'}><img src="${x.src}" width="${x.width}" height="${x.height}" alt="${esc(caption)}" loading="lazy" decoding="async">${zoom?'<span class="cr-photo-label" aria-hidden="true">写真を拡大 ↗</span>':''}</${zoom?'button':'div'}><figcaption>${esc(caption)}</figcaption></figure>`;}
function comparison(group){const rows=data.comparisonRows.filter(x=>x.group===group);return `<div class="cr-comparison" data-cr-comparison><button type="button" class="cr-table-toggle" aria-pressed="false">横表で比べる</button><div class="cr-table-scroll" tabindex="0" role="region" aria-label="花・京・風の仕様比較。横表は横にスクロールできます"><table><caption>花・京・風の仕様比較</caption><thead><tr><th scope="col">項目</th>${['花','京','風'].map((v,i)=>`<th scope="col" class="cr-series-${i}">${v}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr data-spec-key="${r.key}"><th scope="row"><a href="${r.href}">${esc(r.label)} <span aria-hidden="true">↗</span></a>${r.note?`<p class="cr-row-note">${esc(r.note)}</p>`:''}</th>${r.values.map((v,i)=>`<td><span class="cr-mobile-series" aria-hidden="true">${['花','京','風'][i]}</span><span>${esc(v)}</span></td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`;}
const warranty=`<div class="cr-warranty-summary"><div><span class="cr-eyebrow">建物の保証期間</span><p class="cr-years">初期 <strong>10</strong> 年 <span>→</span> 最長 <strong>30</strong> 年</p></div><p>構造耐力上主要な部分と<br>雨水の浸入を防止する部分</p></div><ol class="cr-timeline"><li><span>引渡し → 10年</span><strong>初期保証</strong></li><li><span>10年 → 20年</span><strong>有償で延長</strong></li><li><span>20年 → 30年</span><strong>有償で延長</strong></li></ol><p class="cr-important">延長には点検と、必要な有償メンテナンス工事・所定の手続きが必要です。</p><div class="cr-guarantee-diagram" role="img" aria-label="建物保証の対象を説明する模式図。構造耐力上主要な部分は基礎・柱・梁・耐力壁。雨水の浸入を防止する部分は屋根・外壁・開口部。実際の建物の設計図ではありません。"><svg viewBox="0 0 640 320" aria-hidden="true"><path d="M150 138L320 28L490 138" fill="none" stroke="#527582" stroke-width="12"/><path d="M178 136V286H462V136M178 206H462M230 136V286M405 136V286" fill="none" stroke="#951f2d" stroke-width="7"/><path d="M165 287H475" stroke="#951f2d" stroke-width="18"/><path d="M278 152H335V185H278ZM278 232H335V267H278Z" fill="#eef1ee" stroke="#527582" stroke-width="6"/><path d="M190 214L222 278M412 214L450 278" stroke="#951f2d" stroke-width="5"/></svg><div class="cr-diagram-labels"><p><b>建物を支える部分</b><br>基礎・柱・梁・耐力壁など</p><p><b>雨水の浸入を防ぐ部分</b><br>屋根・外壁・開口部など</p></div><p class="cr-note">保証対象を示す模式図です。個別の設計・施工仕様を示すものではありません。</p></div>`;
function extra(p){let h='';if(p.kind==='warranty')h+=warranty;if(p.comparison)h+=comparison(p.comparison);if(p.prices)h+=`<div class="cr-price-grid">${p.prices.map((s,i)=>`<section class="cr-price-item cr-series-${['花','京','風'].indexOf(s.name)}"><h3>${esc(s.name)}</h3><p class="cr-price">${esc(s.price)}<span>万円</span></p><p>建物本体価格（税込）</p><p>${esc(s.area)}</p><p class="cr-important">土地代別途</p></section>`).join('')}</div>`;if(p.groups)h+=p.groups.map(g=>`<section class="cr-group"><h3>${esc(g.title)}</h3><ul>${g.items.map(v=>`<li>${esc(v)}</li>`).join('')}</ul></section>`).join('');if(p.gallery)h+=`<div class="cr-gallery">${p.gallery.map(x=>photo(x.asset,x.caption)).join('')}</div>`;return h;}
function article(p){return `<article class="cr-page cr-page--${esc(p.kind)}" id="${p.id}" data-cr-page="${p.number}" data-cr-chapter="${p.chapter}" tabindex="-1" aria-labelledby="${p.id}-title"><div class="cr-page-head"><p class="cr-eyebrow">${String(p.number).padStart(2,'0')} / 32 <span>${esc(data.chapters[p.chapter-1].title)}</span></p><h2 id="${p.id}-title">${esc(p.title)}</h2></div><div class="${p.hero?'cr-intro-grid':'cr-intro'}"><div><p class="cr-lead">${esc(p.lead)}</p>${p.hero&&p.notes?.length?`<div class="cr-intro-conditions">${p.notes.map(n=>`<p class="cr-important">${esc(n)}</p>`).join('')}</div>`:''}</div>${p.hero?photo(p.hero.asset,p.hero.caption,true):''}</div>${extra(p)}${p.features.length?`<div class="cr-features${p.kind==='steps'?' cr-features--steps':''}">${p.features.map((f,i)=>`<section class="cr-feature"><div class="cr-feature-copy"><span class="cr-feature-no" aria-hidden="true">${String(i+1).padStart(2,'0')}</span><h3>${esc(f.title)}</h3><p>${esc(f.text)}</p></div>${f.asset?photo(f.asset,f.caption):''}</section>`).join('')}</div>`:''}${!p.hero&&p.notes?.length?`<aside class="cr-conditions" aria-label="適用条件">${p.notes.map(n=>`<p class="cr-important">${esc(n)}</p>`).join('')}</aside>`:''}${links(p.links)}${p.sourceLinks?.length?`<p class="cr-source">製品の機能について：${p.sourceLinks.map(([url,label])=>`<a href="${esc(url)}" target="_blank" rel="noopener">${esc(label)}（外部サイト）</a>`).join(' / ')}</p>`:''}<p class="cr-page-bottom">花鳥風月 やまとの家 <span>${String(p.number).padStart(2,'0')}</span></p></article>`;}
const contents=`<!-- CATALOG CONTENT START --><nav class="cr-toolbar" aria-label="カタログ内の移動"><button type="button" data-cr-cover>表紙</button><button type="button" data-cr-prev aria-label="前のページ">← 前へ</button><button type="button" data-cr-toc aria-haspopup="dialog" aria-controls="catToc">目次</button><span class="cr-position" aria-live="polite"></span><button type="button" data-cr-next aria-label="次のページ">次へ →</button><a href="#price">本編へ ↗</a></nav><div class="cr-content">${data.chapters.map(c=>`<section class="cr-chapter" data-cr-chapter-section="${c.id}" aria-label="${esc(c.title)}"><p class="cr-chapter-title"><span>${String(c.id).padStart(2,'0')}</span>${esc(c.title)}</p>${data.pages.filter(p=>p.chapter===c.id).map(article).join('\n')}</section>`).join('')}<nav class="cr-bottom-nav" aria-label="読み進める"><button type="button" data-cr-prev>← 前へ</button><button type="button" data-cr-toc>目次</button><button type="button" data-cr-next>次へ →</button></nav></div><!-- CATALOG CONTENT END -->`;
const toc=`<!-- CATALOG TOC START --><a class="cr-toc-cover" href="#top">表紙</a><ol class="cr-toc-chapters">${data.chapters.map(c=>`<li><h3>${String(c.id).padStart(2,'0')} ${esc(c.title)}</h3><ol>${data.pages.filter(p=>p.chapter===c.id).map(p=>`<li><a href="#${p.id}"><span>${String(p.number).padStart(2,'0')}</span>${esc(p.title)}</a></li>`).join('')}</ol></li>`).join('')}</ol><!-- CATALOG TOC END -->`;
let html=readFileSync('kodawari.html','utf8');
if(!html.includes('CATALOG CONTENT START')){
 const first=html.indexOf('  <article class="fvs__scene fvs__scene--pc"');const last=html.indexOf('  <a class="fvs__exit"',first);if(first<0||last<0)throw Error('catalog boundary missing');
 html=html.slice(0,first)+contents+'\n\n'+html.slice(last);
 html=html.replace('<section class="fvs" id="top"','<section class="fvs" data-catalog-adopted id="top"');
 html=html.replace('<ol class="fvs__toclist" id="catTocList"></ol>',`<div id="catTocList">${toc}</div>`);
 html=html.replace('<link rel="stylesheet" href="assets/catalog/catalog-hero.css">','<link rel="stylesheet" href="assets/catalog/catalog-hero.css">\n<link rel="stylesheet" href="assets/catalog/adopted/reader.css">\n<script>document.documentElement.classList.add("cr-js");</script>');
 html=html.replace('<script src="assets/catalog/catalog-hero.js" defer>','<script src="assets/catalog/adopted/reader.js" defer></script>\n<script src="assets/catalog/catalog-hero.js" defer>');
 html=html.replace('\n\n<main class="koda"',`\n<dialog class="cr-lightbox" id="crLightbox" aria-label="写真の拡大"><div class="cr-lightbox-tools"><button type="button" data-cr-zoom-reset>全体を見る</button><button type="button" data-cr-zoom-in>拡大</button><button type="button" data-cr-zoom-close aria-label="拡大写真を閉じる">閉じる ×</button></div><div class="cr-lightbox-scroll" tabindex="0"><img alt=""></div><p class="cr-lightbox-caption"></p></dialog>\n\n<main class="koda"`);
}else{html=html.replace(/<!-- CATALOG CONTENT START -->[\s\S]*?<!-- CATALOG CONTENT END -->/,contents).replace(/<!-- CATALOG TOC START -->[\s\S]*?<!-- CATALOG TOC END -->/,toc);}
if(process.argv.includes('--check')){if(html!==readFileSync('kodawari.html','utf8'))throw Error('Catalogue HTML stale');console.log('Catalogue shared data is current: '+data.pages.length+' units / '+data.comparisonRows.length+' comparison rows');}else{writeFileSync('kodawari.html',html);console.log('Rendered catalogue: '+data.pages.length+' units');}
