import assert from 'node:assert/strict';
import {chromium,webkit} from '/Users/takahirokamino/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const base=process.argv[2]||'http://127.0.0.1:8953/',out=new URL('./local/',import.meta.url);await mkdir(out,{recursive:true});const results=[];
const asset=await readFile('assets/top-renewal/sakyo-kitchen-840.webp');
const make=(n)=>({account:{username:'yamatonoie'},posts:Array.from({length:n},(_,i)=>({id:String(1000+i),media_type:i===1?'CAROUSEL_ALBUM':i%3===0?'VIDEO':'IMAGE',caption:`住まいの記録 ${i+1}\n投稿 ${i+1} の本文。図面と建物の確認についてのテスト用原文です。`,timestamp:new Date(Date.UTC(2026,8,20-i,9)).toISOString(),permalink:`https://www.instagram.com/p/TestPost${i}/?source=fixture`,media_url:`https://test.cdninstagram.com/photo-${i}.webp`,thumbnail_url:`https://test.cdninstagram.com/photo-${i}.webp`,children:i===1?[0,1,2].map(j=>({media_type:j===2?'VIDEO':'IMAGE',media_url:`https://test.cdninstagram.com/album-${j}.webp`,thumbnail_url:`https://test.cdninstagram.com/album-${j}.webp`})) : []})).reverse()});
for(const [engine,name,width] of [[chromium,'chromium',1440],[chromium,'chromium',390],[webkit,'webkit',390]]){
 const browser=await engine.launch(),context=await browser.newContext({viewport:{width,height:900},deviceScaleFactor:1,reducedMotion:'reduce'}),page=await context.newPage();let current=make(10),httpStatus=200,failImage=false;const errors=[],checks=[];
 page.on('pageerror',e=>errors.push(e.message));await page.route('**/api/instagram',r=>r.fulfill({status:httpStatus,contentType:'application/json',body:JSON.stringify(current)}));
 await page.route('https://test.cdninstagram.com/**',r=>failImage?r.fulfill({status:404,body:'missing'}):r.fulfill({status:200,contentType:'image/webp',body:asset}));
 await page.goto(base,{waitUntil:'networkidle'});await page.locator('#instagram').scrollIntoViewIfNeeded();await page.waitForFunction(()=>document.querySelector('#instagram').dataset.state==='ready');
 const mount=async payload=>page.evaluate(v=>window.YamatoGallery.mount(v),payload);
 const assertPost=async expected=>{const shown=await page.evaluate(()=>({id:document.querySelector('#igBLayout').dataset.postId,date:document.querySelector('#igBDate').dateTime,kind:document.querySelector('#igBKind').textContent,lead:document.querySelector('#igBLead').textContent,href:document.querySelector('#igBOfficial').href}));assert.equal(shown.id,expected.id);assert.equal(shown.date,expected.timestamp);assert.equal(shown.href,expected.permalink.split('?')[0]);assert(expected.caption.includes(shown.lead));};
 const sorted=[...current.posts].sort((a,b)=>Date.parse(b.timestamp)-Date.parse(a.timestamp));await assertPost(sorted[0]);await page.locator('#igBNext').click();await assertPost(sorted[1]);
 assert.equal(await page.locator('#igBNeighbors button').count(),3);assert.equal(new Set(await page.locator('#igBNeighbors button').evaluateAll(e=>e.map(b=>b.dataset.postId))).size,3);
 await page.locator('#igBOpen').click();assert.equal(await page.locator('#igDialogCaption').textContent(),sorted[1].caption);assert.equal(await page.locator('#igDialogLink').getAttribute('href'),sorted[1].permalink.split('?')[0]);
 await page.locator('#igPhotoNext').click();assert.equal(await page.locator('#igPhotoCount').textContent(),'2 / 3');await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#igPhotoCount').textContent(),'3 / 3');assert(await page.locator('#igPhotoNext').isDisabled());
 await page.locator('#igPostNext').click();await assertPost(sorted[2]);assert.equal(await page.locator('#igDialogCaption').textContent(),sorted[2].caption);assert(await page.locator('#igPhotoNav').isHidden());
 await page.locator('#igDialog').evaluate(e=>{const f=[...e.querySelectorAll('button:not([disabled]),a[href]')].filter(x=>x.getClientRects().length);f.at(-1).focus();});await page.keyboard.press('Tab');assert(await page.locator('#igDialog [data-close]').evaluate(e=>e===document.activeElement));
 await page.keyboard.press('Escape');assert(await page.locator('#igDialog').evaluate(e=>!e.open));assert(await page.locator('#igBOpen').evaluate(e=>e===document.activeElement));checks.push('10 latest posts: identity, metadata, permalink, distinct neighbors, album, modal post switching, Tab trap, Esc/focus return');
 for(const n of [0,1,2,3]){await mount(make(n));assert.equal(await page.locator('#igBNeighbors button').count(),n?Math.min(n-1,3):0);
  assert.equal(await page.locator('#igBNav').isVisible(),n>1);assert.equal(await page.locator('#igBLayout').isVisible(),n>0);assert.equal(await page.locator('#instagram').getAttribute('data-state'),n?'ready':'empty');if(n===1){await page.locator('#igBOpen').click();assert(await page.locator('#igPostNext').isHidden());await page.keyboard.press('Escape');}}
 checks.push('0/1/2/3 posts: empty differs from error; navigation and neighbors match available records');
 const long=make(1);long.posts[0].caption='長い投稿の見出し\n'+'条件と説明を省略しないテスト本文。'.repeat(120);long.posts[0].caption=long.posts[0].caption.slice(0,2200);await mount(long);assert((await page.locator('#igBExcerpt').textContent()).length<230);await page.locator('#igBOpen').click();assert.equal(await page.locator('#igDialogCaption').textContent(),long.posts[0].caption);await page.keyboard.press('Escape');
 long.posts[0].caption='';await mount(long);assert(await page.locator('#igBLead').isHidden());assert.equal(await page.locator('#igBExcerpt').textContent(),'この投稿には本文がありません。');
 long.posts[0].caption='<img src=x onerror="window.badCaption=true">\n本文';await mount(long);assert.equal(await page.locator('#igBLead img').count(),0);assert.equal(await page.evaluate(()=>Boolean(window.badCaption)),false);checks.push('Long, empty and HTML-like captions: excerpt bounded, full original readable, no HTML execution');
 failImage=true;const missing=make(2);missing.posts.forEach(p=>{p.media_url=p.media_url.replace('.webp','-missing.webp');p.thumbnail_url=p.thumbnail_url.replace('.webp','-missing.webp');});await mount(missing);await page.waitForFunction(()=>document.querySelector('#igBCover').textContent.includes('画像を読み込めませんでした。'));assert(await page.locator('#igBOfficial').isVisible());assert.equal(await page.locator('#igBLayout').getAttribute('data-post-id'),'1000');failImage=false;await mount(make(2));
 const invalid=make(3);invalid.posts.push({...invalid.posts[0]});invalid.posts.push({...invalid.posts[0],id:'bad',permalink:'javascript:alert(1)'});assert.equal((await mount(invalid)).displayed,3);const bad=make(1);bad.posts[0].media_url='http://invalid.local/image';bad.posts[0].thumbnail_url='https://evil.example/image';assert.equal(await page.evaluate(v=>{try{window.YamatoGallery.mount(v);return false}catch{return true}},bad),true);checks.push('Media failures retain original post action; duplicate IDs and unsafe media/permalinks rejected');
 await mount(make(3));await page.locator('#igBNeighbors button').first().click();assert(await page.locator('#igBOpen').evaluate(e=>e===document.activeElement));await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#igBLayout').getAttribute('data-post-id'),'1002');await page.keyboard.press('ArrowLeft');assert.equal(await page.locator('#igBLayout').getAttribute('data-post-id'),'1001');checks.push('Neighbor selection keeps focus; arrow keys select matching posts');
 current={error:'temporarily_unavailable',posts:[]};httpStatus=503;await page.reload({waitUntil:'domcontentloaded'});await page.locator('#instagram').scrollIntoViewIfNeeded();await page.waitForFunction(()=>document.querySelector('#instagram').dataset.state==='error');assert(await page.locator('#igBRetry').isVisible());assert.equal(await page.locator('#igBEmptyText').textContent(),'投稿を読み込めませんでした。時間をおいて、もう一度お試しください。');current=make(2);httpStatus=200;await page.locator('#igBRetry').click();await page.waitForFunction(()=>document.querySelector('#instagram').dataset.state==='ready');assert.equal(await page.locator('#igBNeighbors button').count(),1);checks.push('HTTP failure, retry and successful recovery');
 const guideLinks=await page.locator('#entrance a').evaluateAll(e=>e.map(a=>a.getAttribute('href')));assert.deepEqual(guideLinks,['lots-preview.html?view=list','lots-preview.html?view=estimate','kodawari.html','move-to-nara-preview.html','#lineup','works.html','model.html','kodawari.html','move-to-nara-preview.html']);assert.equal(await page.locator('#entrance button').count(),0);assert.equal(await page.locator('#entrance [data-clone]').count(),0);checks.push('All nine guide routes in adopted order, static list without motion controls or clones');
 await page.locator('#menuToggle').click();assert(await page.locator('#siteMenu').isVisible());await page.keyboard.press('Escape');assert(await page.locator('#siteMenu').isHidden());await page.locator('#visit [data-contact="docs"]').click();assert(await page.locator('#contactDialog').evaluate(e=>e.open));await page.keyboard.press('Escape');checks.push('Unchanged global menu and enquiry preview dialog');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);results.push({engine:name,width,checks,errors});await browser.close();console.log(JSON.stringify({engine:name,width,checks:checks.length}));
}
const browser=await chromium.launch(),page=await browser.newPage({viewport:{width:390,height:844},javaScriptEnabled:false});await page.goto(base,{waitUntil:'networkidle'});await page.locator('#entrance').scrollIntoViewIfNeeded();assert.equal(await page.locator('#entrance a').count(),9);await page.locator('#instagram').scrollIntoViewIfNeeded();assert(await page.getByText('公式アカウントで、住まいの写真や動画をご覧いただけます。').isVisible());assert(await page.locator('#instagram a').first().isVisible());await browser.close();results.push({engine:'chromium',noJS:true,checks:['All nine static routes and official Instagram exit remain usable']});
await writeFile(new URL('functional.json',out),JSON.stringify({base,results},null,2));console.log('Adopted entrance and Instagram functional checks passed.');
